package com.mbeddr.ext.utils.tools;

/*Generated by MPS */
//AND CORRECTED THEN!

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;

public class YicesRawResult {
  private boolean satisfiable;
  private List<Integer> unsatCoreIds =new ArrayList<Integer>();
  private Map<String, String> vars2Vals = new HashMap<String, String>();

  public YicesRawResult() {
  }

  public void setSatisfiable(boolean isSatisfiable) {
    satisfiable = isSatisfiable;
  }

  public void addUnsatCoreID(int id) {
    unsatCoreIds.add(id);
  }

  public List<Integer> getUnsatCoreIDs() {
    return unsatCoreIds;
  }

  public boolean isSatisfiable() {
    return satisfiable;
  }

  public void addVarValMapping(String varName, String val) {
    vars2Vals.put(varName, val);
  }

  public List<String> getVarNames() {
    Set<String> set = vars2Vals.keySet();
    ArrayList<String> res = new ArrayList<String>();
    res.addAll(set);
    return res;
  }

  public List<Pair<String, String>> getEvidence() {
    final List<Pair<String, String>> evidence = new ArrayList<Pair<String, String>>();
    
    for(String name : getVarNames())
    {
    	evidence.add(new Pair<String, String>(name, getVariableValue(name)));
    }
    
    return evidence;
  }

  public String getVariableValue(String varName) {
    return vars2Vals.get(varName);
  }
}
